" 精简 Vim 配置
set nocompatible
syntax on
filetype plugin indent on

" 基础设置
set number
set relativenumber
set cursorline
set showcmd
set showmatch
set wildmenu
set wildmode=longest:full,full
set laststatus=2
set ruler
set backspace=indent,eol,start

" 缩进
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

" 搜索
set hlsearch
set incsearch
set ignorecase
set smartcase

" 编码
set encoding=utf-8
set fileencodings=utf-8,gbk,gb2312,latin1

" 性能
set lazyredraw
set ttyfast
set updatetime=300

" 备份
set nobackup
set noswapfile
set nowritebackup

" 状态栏
set statusline=%f\ %m%r%h%w\ [%{&ff}]\ [%Y]\ [%l/%L,\ %c]\ [%p%%]

" 快捷键
let mapleader = " "
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader><space> :nohlsearch<CR>

" 文件类型缩进
autocmd FileType javascript,typescript,json,yaml,html,css setlocal shiftwidth=2 softtabstop=2
autocmd FileType go setlocal noexpandtab
