networks:
  localNetwork:
    external: true
services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    networks:
      - localNetwork
    # ports:
    #   - 80:80
    restart: always
    volumes:
      - ./data:/data
